# Generated by Django 5.1.1 on 2024-09-16 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_moodentry_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesananEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pesanan', models.CharField(max_length=255)),
                ('time', models.DateField(auto_now_add=True)),
                ('keterangan', models.TextField()),
                ('quantitas', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
